services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - my-network
    ports:
      - "3307:3306"  # Port trên host:Port trên container
    volumes:
      - /d/t3h/docker/mysql-data:/var/lib/mysql

  springboot:
    image: my-springboot-app  # Spring Boot app sẽ build từ Dockerfile
    container_name: springboot-container
    depends_on:
      - mysql  # Chạy mysql container trước khi bắt đầu springboot
    networks:
      - my-network
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://my-mysql-container:3306/insuranceclaim?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456

networks:
  my-network:
    driver: bridge
