/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.34
 * Generated at: 2025-03-17 12:43:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1736349412000L));
    _jspx_dependants.put("jar:file:/D:/T3h/LJava2411/github/LJava2411/LJava2411/servlet/apache-tomcat-10.1.34-windows-x64/apache-tomcat-10.1.34/webapps/ROOT/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602848772000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("    <title>Trang chủ</title>\r\n");
      out.write("\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/img/favicon.ico\" rel=\"shortcut icon\" type=\"image/x-icon\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap v5.0.1 -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/css/bootstrap.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/js/bootstrap.bundle.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap Icons v1.5.0 -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/css/bootstrap-icons.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom Styles -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/css/styles.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header class=\"section-header\">\r\n");
      out.write("    <section class=\"header-main border-bottom\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row align-items-center\">\r\n");
      out.write("                <div class=\"col-lg-3 py-3\">\r\n");
      out.write("                    <a class=\"text-body\" href=\"./home.html\">\r\n");
      out.write("                        <h3>Shop Bán Sách</h3>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div> <!-- col.// -->\r\n");
      out.write("                <div class=\"col-lg-4 col-xl-5\">\r\n");
      out.write("                    <form action=\"#\" class=\"search\">\r\n");
      out.write("                        <div class=\"input-group w-100\">\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" placeholder=\"Nhập từ khóa cần tìm ...\">\r\n");
      out.write("                            <button class=\"btn btn-primary\" type=\"button\">\r\n");
      out.write("                                <i class=\"bi bi-search\"></i>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div> <!-- col.// -->\r\n");
      out.write("                <div class=\"col-lg-5 col-xl-4\">\r\n");
      out.write("                    <ul class=\"nav col-12 col-lg-auto my-2 my-lg-0 justify-content-center justify-content-lg-end text-small\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\" class=\"nav-link text-body\">\r\n");
      out.write("                                <i class=\"bi bi-person d-block text-center fs-3\"></i>\r\n");
      out.write("                                Tài khoản\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\" class=\"nav-link text-body\">\r\n");
      out.write("                                <i class=\"bi bi-list-check d-block text-center fs-3\"></i>\r\n");
      out.write("                                Đơn hàng\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\" class=\"nav-link text-body\">\r\n");
      out.write("                                <i class=\"bi bi-cart d-block text-center fs-3\"></i>\r\n");
      out.write("                                Giỏ hàng\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div> <!-- col.// -->\r\n");
      out.write("            </div> <!-- row.// -->\r\n");
      out.write("        </div> <!-- container.// -->\r\n");
      out.write("    </section> <!-- header-main.// -->\r\n");
      out.write("</header> <!-- section-header.// -->\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-main navbar-expand-lg navbar-light border-bottom\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\"\r\n");
      out.write("                aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("            <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("                       aria-expanded=\"false\">\r\n");
      out.write("                        <strong><i class=\"bi bi-list\"></i> Danh mục sản phẩm</strong>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Sách giáo khoa</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Sách khoa học</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Truyện tranh</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Tiểu thuyết</a></li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <hr class=\"dropdown-divider\">\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Tất cả danh mục</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#\">Sản phẩm mới</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#\">Sản phẩm bán chạy</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#\">Khuyến mãi</a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <a class=\"btn btn-light me-2\" href=\"#\" role=\"button\">Đăng ký</a>\r\n");
      out.write("            <a class=\"btn btn-primary\" href=\"#\" role=\"button\">Đăng nhập</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div> <!-- container.// -->\r\n");
      out.write("</nav> <!-- navbar-main.// -->\r\n");
      out.write("\r\n");
      out.write("<section class=\"section-content mb-2\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <header class=\"section-heading py-4 d-flex justify-content-between\">\r\n");
      out.write("            <h3 class=\"section-title\">Danh mục sản phẩm</h3>\r\n");
      out.write("            <a class=\"btn btn-secondary\" href=\"#\" role=\"button\" style=\"height: fit-content;\">Xem tất cả</a>\r\n");
      out.write("        </header> <!-- section-heading.// -->\r\n");
      out.write("        <div class=\"row item-grid\">\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <div class=\"card mb-4\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <a href=\"#\" class=\"stretched-link\">\r\n");
      out.write("                            <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                <img src=\"img/50px.png\">\r\n");
      out.write("                                <span class=\"category-title ms-3\">Sách giáo khoa</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> <!-- col.// -->\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <div class=\"card mb-4\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <a href=\"#\" class=\"stretched-link\">\r\n");
      out.write("                            <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                <img src=\"img/50px.png\">\r\n");
      out.write("                                <span class=\"category-title ms-3\">Sách giáo khoa</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> <!-- col.// -->\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <div class=\"card mb-4\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <a href=\"#\" class=\"stretched-link\">\r\n");
      out.write("                            <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                <img src=\"img/50px.png\">\r\n");
      out.write("                                <span class=\"category-title ms-3\">Sách giáo khoa</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> <!-- col.// -->\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <div class=\"card mb-4\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <a href=\"#\" class=\"stretched-link\">\r\n");
      out.write("                            <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                <img src=\"img/50px.png\">\r\n");
      out.write("                                <span class=\"category-title ms-3\">Sách giáo khoa</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> <!-- col.// -->\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <div class=\"card mb-4\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <a href=\"#\" class=\"stretched-link\">\r\n");
      out.write("                            <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                <img src=\"img/50px.png\">\r\n");
      out.write("                                <span class=\"category-title ms-3\">Sách giáo khoa</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> <!-- col.// -->\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <div class=\"card mb-4\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <a href=\"#\" class=\"stretched-link\">\r\n");
      out.write("                            <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                <img src=\"img/50px.png\">\r\n");
      out.write("                                <span class=\"category-title ms-3\">Sách giáo khoa</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> <!-- col.// -->\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <div class=\"card mb-4\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <a href=\"#\" class=\"stretched-link\">\r\n");
      out.write("                            <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                <img src=\"img/50px.png\">\r\n");
      out.write("                                <span class=\"category-title ms-3\">Sách giáo khoa</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> <!-- col.// -->\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <div class=\"card mb-4\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <a href=\"#\" class=\"stretched-link\">\r\n");
      out.write("                            <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                <img src=\"img/50px.png\">\r\n");
      out.write("                                <span class=\"category-title ms-3\">Sách giáo khoa</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> <!-- col.// -->\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <div class=\"card mb-4\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <a href=\"#\" class=\"stretched-link\">\r\n");
      out.write("                            <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                <img src=\"img/50px.png\">\r\n");
      out.write("                                <span class=\"category-title ms-3\">Sách giáo khoa</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> <!-- col.// -->\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <div class=\"card mb-4\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <a href=\"#\" class=\"stretched-link\">\r\n");
      out.write("                            <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                <img src=\"img/50px.png\">\r\n");
      out.write("                                <span class=\"category-title ms-3\">Sách giáo khoa</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> <!-- col.// -->\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <div class=\"card mb-4\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <a href=\"#\" class=\"stretched-link\">\r\n");
      out.write("                            <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                <img src=\"img/50px.png\">\r\n");
      out.write("                                <span class=\"category-title ms-3\">Sách giáo khoa</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> <!-- col.// -->\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <div class=\"card mb-4\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <a href=\"#\" class=\"stretched-link\">\r\n");
      out.write("                            <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                <img src=\"img/50px.png\">\r\n");
      out.write("                                <span class=\"category-title ms-3\">Sách giáo khoa</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> <!-- col.// -->\r\n");
      out.write("        </div> <!-- row.// -->\r\n");
      out.write("    </div> <!-- container.// -->\r\n");
      out.write("</section> <!-- section-content.// -->\r\n");
      out.write("\r\n");
      out.write("<section class=\"section-content mb-5\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <header class=\"section-heading py-4 d-flex justify-content-between\">\r\n");
      out.write("            <h3 class=\"section-title\">Sản phẩm mới nhất</h3>\r\n");
      out.write("            <a class=\"btn btn-secondary\" href=\"#\" role=\"button\" style=\"height: fit-content;\">Xem tất cả</a>\r\n");
      out.write("        </header> <!-- section-heading.// -->\r\n");
      out.write("        <div class=\"row item-grid\">\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <div class=\"card p-3 mb-4\">\r\n");
      out.write("                    <a href=\"#\" class=\"img-wrap text-center\">\r\n");
      out.write("                        <img class=\"img-fluid\" src=\"img/200px.png\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <figcaption class=\"info-wrap mt-2\">\r\n");
      out.write("                        <a href=\"#\" class=\"title\">Tên một sản phẩm</a>\r\n");
      out.write("                        <div class=\"price mt-1 fw-bold\">450.000₫</div>\r\n");
      out.write("                    </figcaption>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> <!-- col.// -->\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <div class=\"card p-3 mb-4\">\r\n");
      out.write("                    <a href=\"#\" class=\"img-wrap text-center\">\r\n");
      out.write("                        <img class=\"img-fluid\" src=\"img/200px.png\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <figcaption class=\"info-wrap mt-2\">\r\n");
      out.write("                        <a href=\"#\" class=\"title\">Tên một sản phẩm</a>\r\n");
      out.write("                        <div class=\"price mt-1 fw-bold\">450.000₫</div>\r\n");
      out.write("                    </figcaption>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> <!-- col.// -->\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <div class=\"card p-3 mb-4\">\r\n");
      out.write("                    <a href=\"#\" class=\"img-wrap text-center\">\r\n");
      out.write("                        <img class=\"img-fluid\" src=\"img/200px.png\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <figcaption class=\"info-wrap mt-2\">\r\n");
      out.write("                        <a href=\"#\" class=\"title\">Tên một sản phẩm</a>\r\n");
      out.write("                        <div class=\"price mt-1 fw-bold\">450.000₫</div>\r\n");
      out.write("                    </figcaption>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> <!-- col.// -->\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <div class=\"card p-3 mb-4\">\r\n");
      out.write("                    <a href=\"#\" class=\"img-wrap text-center\">\r\n");
      out.write("                        <img class=\"img-fluid\" src=\"img/200px.png\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <figcaption class=\"info-wrap mt-2\">\r\n");
      out.write("                        <a href=\"#\" class=\"title\">Tên một sản phẩm</a>\r\n");
      out.write("                        <div class=\"price mt-1 fw-bold\">450.000₫</div>\r\n");
      out.write("                    </figcaption>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> <!-- col.// -->\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <div class=\"card p-3 mb-4\">\r\n");
      out.write("                    <a href=\"#\" class=\"img-wrap text-center\">\r\n");
      out.write("                        <img class=\"img-fluid\" src=\"img/200px.png\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <figcaption class=\"info-wrap mt-2\">\r\n");
      out.write("                        <a href=\"#\" class=\"title\">Tên một sản phẩm</a>\r\n");
      out.write("                        <div class=\"price mt-1 fw-bold\">450.000₫</div>\r\n");
      out.write("                    </figcaption>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> <!-- col.// -->\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <div class=\"card p-3 mb-4\">\r\n");
      out.write("                    <a href=\"#\" class=\"img-wrap text-center\">\r\n");
      out.write("                        <img class=\"img-fluid\" src=\"img/200px.png\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <figcaption class=\"info-wrap mt-2\">\r\n");
      out.write("                        <a href=\"#\" class=\"title\">Tên một sản phẩm</a>\r\n");
      out.write("                        <div class=\"price mt-1 fw-bold\">450.000₫</div>\r\n");
      out.write("                    </figcaption>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> <!-- col.// -->\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <div class=\"card p-3 mb-4\">\r\n");
      out.write("                    <a href=\"#\" class=\"img-wrap text-center\">\r\n");
      out.write("                        <img class=\"img-fluid\" src=\"img/200px.png\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <figcaption class=\"info-wrap mt-2\">\r\n");
      out.write("                        <a href=\"#\" class=\"title\">Tên một sản phẩm</a>\r\n");
      out.write("                        <div class=\"price mt-1 fw-bold\">450.000₫</div>\r\n");
      out.write("                    </figcaption>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> <!-- col.// -->\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <div class=\"card p-3 mb-4\">\r\n");
      out.write("                    <a href=\"#\" class=\"img-wrap text-center\">\r\n");
      out.write("                        <img class=\"img-fluid\" src=\"img/200px.png\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <figcaption class=\"info-wrap mt-2\">\r\n");
      out.write("                        <a href=\"#\" class=\"title\">Tên một sản phẩm</a>\r\n");
      out.write("                        <div class=\"price mt-1 fw-bold\">450.000₫</div>\r\n");
      out.write("                    </figcaption>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> <!-- col.// -->\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <div class=\"card p-3 mb-4\">\r\n");
      out.write("                    <a href=\"#\" class=\"img-wrap text-center\">\r\n");
      out.write("                        <img class=\"img-fluid\" src=\"img/200px.png\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <figcaption class=\"info-wrap mt-2\">\r\n");
      out.write("                        <a href=\"#\" class=\"title\">Tên một sản phẩm</a>\r\n");
      out.write("                        <div class=\"price mt-1 fw-bold\">450.000₫</div>\r\n");
      out.write("                    </figcaption>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> <!-- col.// -->\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <div class=\"card p-3 mb-4\">\r\n");
      out.write("                    <a href=\"#\" class=\"img-wrap text-center\">\r\n");
      out.write("                        <img class=\"img-fluid\" src=\"img/200px.png\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <figcaption class=\"info-wrap mt-2\">\r\n");
      out.write("                        <a href=\"#\" class=\"title\">Tên một sản phẩm</a>\r\n");
      out.write("                        <div class=\"price mt-1 fw-bold\">450.000₫</div>\r\n");
      out.write("                    </figcaption>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> <!-- col.// -->\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <div class=\"card p-3 mb-4\">\r\n");
      out.write("                    <a href=\"#\" class=\"img-wrap text-center\">\r\n");
      out.write("                        <img class=\"img-fluid\" src=\"img/200px.png\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <figcaption class=\"info-wrap mt-2\">\r\n");
      out.write("                        <a href=\"#\" class=\"title\">Tên một sản phẩm</a>\r\n");
      out.write("                        <div class=\"price mt-1 fw-bold\">450.000₫</div>\r\n");
      out.write("                    </figcaption>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> <!-- col.// -->\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <div class=\"card p-3 mb-4\">\r\n");
      out.write("                    <a href=\"#\" class=\"img-wrap text-center\">\r\n");
      out.write("                        <img class=\"img-fluid\" src=\"img/200px.png\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <figcaption class=\"info-wrap mt-2\">\r\n");
      out.write("                        <a href=\"#\" class=\"title\">Tên một sản phẩm</a>\r\n");
      out.write("                        <div class=\"price mt-1 fw-bold\">450.000₫</div>\r\n");
      out.write("                    </figcaption>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> <!-- col.// -->\r\n");
      out.write("        </div> <!-- row.// -->\r\n");
      out.write("    </div> <!-- container.// -->\r\n");
      out.write("</section> <!-- section-content.// -->\r\n");
      out.write("\r\n");
      out.write("<footer class=\"section-footer\">\r\n");
      out.write("    <section class=\"footer-top py-5 bg-light\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <aside class=\"col-sm-6 col-lg-3\">\r\n");
      out.write("                    <h6 class=\"pb-2\">Giới thiệu</h6>\r\n");
      out.write("                    <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li><a href=\"#\">Về Shop</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Tuyển dụng</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Chính sách thanh toán</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Chính sách bảo mật</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Giải quyết khiếu nại</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Hợp tác</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </aside>\r\n");
      out.write("                <aside class=\"col-sm-6 col-lg-3\">\r\n");
      out.write("                    <h6 class=\"pb-2\">Hỗ trợ khách hàng</h6>\r\n");
      out.write("                    <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li>Hotline: 1900-80xx</li>\r\n");
      out.write("                        <li><a href=\"#\">Câu hỏi thường gặp</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Hướng dẫn đặt hàng</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Phương thức vận chuyển</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Chính sách đổi trả</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </aside>\r\n");
      out.write("                <aside class=\"col-lg-5\">\r\n");
      out.write("                    <h6 class=\"pb-2\">Đăng ký nhận tin</h6>\r\n");
      out.write("                    <form action=\"#\">\r\n");
      out.write("                        <div class=\"input-group w-100\">\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" placeholder=\"Email của bạn ...\">\r\n");
      out.write("                            <button class=\"btn btn-primary\" type=\"button\">\r\n");
      out.write("                                Đăng ký\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </aside>\r\n");
      out.write("            </div> <!-- row.// -->\r\n");
      out.write("        </div> <!-- container.// -->\r\n");
      out.write("    </section> <!-- footer-top.// -->\r\n");
      out.write("\r\n");
      out.write("    <section class=\"footer-bottom text-center bg-light border-top py-3\">\r\n");
      out.write("        <div class=\"container-fluid\">© 2021 — Shop Bán Sách</div> <!-- container-fluid.// -->\r\n");
      out.write("    </section> <!-- footer-bottom.// -->\r\n");
      out.write("</footer> <!-- section-footer.// -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /index.jsp(12,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("contextPath");
    // /index.jsp(12,0) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/index.jsp(12,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }
}
